server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://carrinho-db:3306/carrinho?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Sao_Paulo
    username: carrinho
    password: carrinho_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: true

management:
  endpoints.web.exposure.include: health,info
