server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://pagamento-db:3306/pagamento?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Sao_Paulo
    username: pagamento
    password: pagamento_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
